BATTLE_TOWER_TIER_OFFSET = 9000
BATTLE_TOWER_TRAINER_OFFSET = 9100
BATTLE_TOWER_NUM_TIERS = 10
BATTLE_TOWER_TRAINERS_PER_TIER = 7
BATTLE_TOWER_NUM_TRAINERS = BATTLE_TOWER_NUM_TIERS * BATTLE_TOWER_TRAINERS_PER_TIER

BATTLE_TOWER_TRAINERS = [
    ("Fisher", "Hanson"),
    ("Pokemaniac", "Sawyer"),
    ("Guitarist", "Masuda"),
    ("Scientist", "Nickel"),
    ("Pokefan", "Olson"),
    ("Lass", "Zaborowski"),
    ("Youngster", "Wright"),
    ("Hiker", "Alexander"),
    ("Teacher", "Kawakami"),
    ("Pokefan", "Bickett"),
    ("Kimono Girl", "Saito"),
    ("Boarder", "Crawford"),
    ("Picnicker", "Diaz"),
    ("Biker", "Erickson"),
    ("Juggler", "Fairfield"),
    ("Pokefan", "Hunter"),
    ("Firebreather", "Hill"),
    ("Swimmer", "Javier"),
    ("Swimmer", "Kaufman"),
    ("Skier", "Lancaster"),
    ("Camper", "McMahill"),
    ("Gentleman", "Obrien"),
    ("Beauty", "Frost"),
    ("Super Nerd", "Morse"),
    ("Blackbelt", "Yufune"),
    ("Cool Trainer", "Rajan"),
    ("Officer", "Rodriguez"),
    ("Psychic", "Santiago"),
    ("Pokefan", "Stock"),
    ("Scientist", "Thurman"),
    ("Beauty", "Valentino"),
    ("Camper", "Wagner"),
    ("Bird Keeper", "Yates"),
    ("Picnicker", "Andrews"),
    ("Pokemaniac", "Bahn"),
    ("Scientist", "Mori"),
    ("Sage", "Buckman"),
    ("Schoolboy", "Cobb"),
    ("Fisher", "Hughes"),
    ("Kimono Girl", "Arita"),
    ("Psychic", "Easton"),
    ("Camper", "Freeman"),
    ("Lass", "Giese"),
    ("Gentleman", "Hatcher"),
    ("Pokefan", "Jackson"),
    ("Pokemaniac", "Kahn"),
    ("Youngster", "Leong"),
    ("Teacher", "Marino"),
    ("Sailor", "Newman"),
    ("Blackbelt", "Nguyen"),
    ("Super Nerd", "Ogden"),
    ("Cool Trainer", "Park"),
    ("Swimmer", "Raine"),
    ("Bird Keeper", "Sells"),
    ("Boarder", "Rockwell"),
    ("Lass", "Thornton"),
    ("Officer", "Turner"),
    ("Skier", "Van Dyke"),
    ("Schoolboy", "Walker"),
    ("Swimmer", "Meyer"),
    ("Youngster", "Johnson"),
    ("Guitarist", "Adams"),
    ("Bug Catcher", "Smith"),
    ("Bug Catcher", "Tajiri"),
    ("Pokemaniac", "Baker"),
    ("Scientist", "Collins"),
    ("Super Nerd", "Smart"),
    ("Swimmer", "Dykstra"),
    ("Biker", "Eaton"),
    ("Firebreather", "Wong"),
]

assert len(BATTLE_TOWER_TRAINERS) == BATTLE_TOWER_NUM_TRAINERS
