"""Tracker flag groups uploaded to data storage for the Archipelago map tracker."""

from .data import data

TRACKER_EVENT_FLAGS = [
    "EVENT_GOT_KENYA",
    "EVENT_GAVE_KENYA",
    "EVENT_JASMINE_RETURNED_TO_GYM",
    "EVENT_DECIDED_TO_HELP_LANCE",
    "EVENT_CLEARED_ROCKET_HIDEOUT",
    "EVENT_CLEARED_RADIO_TOWER",
    "EVENT_BEAT_ELITE_FOUR",
    "EVENT_RESTORED_POWER_TO_KANTO",
    "EVENT_BLUE_GYM_TRACKER",
    "EVENT_BEAT_RED",
    "EVENT_CLEARED_SLOWPOKE_WELL",
    "EVENT_HERDED_FARFETCHD",
    "EVENT_RELEASED_THE_BEASTS",
    "EVENT_BEAT_FALKNER",
    "EVENT_BEAT_BUGSY",
    "EVENT_BEAT_WHITNEY",
    "EVENT_BEAT_MORTY",
    "EVENT_BEAT_JASMINE",
    "EVENT_BEAT_CHUCK",
    "EVENT_BEAT_PRYCE",
    "EVENT_BEAT_CLAIR",
    "EVENT_BEAT_BROCK",
    "EVENT_BEAT_MISTY",
    "EVENT_BEAT_LTSURGE",
    "EVENT_BEAT_ERIKA",
    "EVENT_BEAT_JANINE",
    "EVENT_BEAT_SABRINA",
    "EVENT_BEAT_BLAINE",
    "EVENT_BEAT_BLUE",
    "EVENT_FAST_SHIP_FOUND_GIRL",
    "EVENT_GOT_MYSTERY_EGG_FROM_MR_POKEMON",
    "EVENT_BILL_ACTIVATED_TIME_CAPSULE",
]

EVENT_FLAG_MAP = {data.event_flags[event]: event for event in TRACKER_EVENT_FLAGS}

TRACKER_EVENT_FLAGS_2 = [
    "EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY",
    "EVENT_SAW_SUICUNE_ON_ROUTE_42",
    "EVENT_SAW_SUICUNE_ON_ROUTE_36",
    "EVENT_BEAT_RIVAL_IN_MT_MOON",
    "EVENT_GOT_EON_MAIL_FROM_EUSINE",
    "EVENT_BEAT_CHERRYGROVE_RIVAL",
    "EVENT_BEAT_AZALEA_RIVAL",
    "EVENT_RIVAL_BURNED_TOWER",
    "EVENT_BEAT_GOLDENROD_UNDERGROUND_RIVAL",
    "EVENT_BEAT_VICTORY_ROAD_RIVAL",
    "EVENT_BEAT_RIVAL_IN_INDIGO_PLATEAU",
    "EVENT_DEFEATED_ROUTE_24_ROCKET",
    "EVENT_GOT_ALL_UNOWN",
    "EVENT_OBTAINED_DIPLOMA",
    "EVENT_BEAT_ROCKET_EXECUTIVEM_3",
    "EVENT_SOLVED_KABUTO_PUZZLE",
    "EVENT_SOLVED_OMANYTE_PUZZLE",
    "EVENT_SOLVED_AERODACTYL_PUZZLE",
    "EVENT_SOLVED_HO_OH_PUZZLE",
    "EVENT_GAVE_MYSTERY_EGG_TO_ELM",
    "EVENT_USED_TELEPORT_ABRA",
]

EVENT_FLAG_MAP_2 = {data.event_flags[event]: event for event in TRACKER_EVENT_FLAGS_2}

TRACKER_STATIC_EVENT_FLAGS = [
    "EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE",
    "EVENT_FOUGHT_SUDOWOODO",
    "EVENT_LAKE_OF_RAGE_RED_GYARADOS",
    "EVENT_FOUGHT_HO_OH",
    "EVENT_FOUGHT_LUGIA",
    "EVENT_FOUGHT_SUICUNE",
    "EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_1",
    "EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_2",
    "EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_3",
    "EVENT_GOT_SHUCKIE",
    "EVENT_GOT_EEVEE",
    "EVENT_GOT_DRATINI",
    "EVENT_TOGEPI_HATCHED",
    "EVENT_GOT_TYROGUE_FROM_KIYO",
    "EVENT_UNION_CAVE_B2F_LAPRAS",
    "EVENT_FOUGHT_CELEBI",
    "EVENT_GOT_ODD_EGG",
    "EVENT_STATIC_GOLDENROD_GAME_CORNER_1",
    "EVENT_STATIC_GOLDENROD_GAME_CORNER_2",
    "EVENT_STATIC_GOLDENROD_GAME_CORNER_3",
    "EVENT_STATIC_CELADON_GAME_CORNER_PRIZE_ROOM_1",
    "EVENT_STATIC_CELADON_GAME_CORNER_PRIZE_ROOM_2",
    "EVENT_STATIC_CELADON_GAME_CORNER_PRIZE_ROOM_3",
    "EVENT_FOUGHT_SNORLAX",
]

STATIC_EVENT_FLAG_MAP = {data.event_flags[event]: event for event in TRACKER_STATIC_EVENT_FLAGS}

TRACKER_ROCKET_TRAP_EVENTS = [
    "EVENT_EXPLODING_TRAP_1",
    "EVENT_EXPLODING_TRAP_2",
    "EVENT_EXPLODING_TRAP_3",
    "EVENT_EXPLODING_TRAP_4",
    "EVENT_EXPLODING_TRAP_5",
    "EVENT_EXPLODING_TRAP_6",
    "EVENT_EXPLODING_TRAP_7",
    "EVENT_EXPLODING_TRAP_8",
    "EVENT_EXPLODING_TRAP_9",
    "EVENT_EXPLODING_TRAP_10",
    "EVENT_EXPLODING_TRAP_11",
    "EVENT_EXPLODING_TRAP_12",
    "EVENT_EXPLODING_TRAP_13",
    "EVENT_EXPLODING_TRAP_14",
    "EVENT_EXPLODING_TRAP_15",
    "EVENT_EXPLODING_TRAP_16",
    "EVENT_EXPLODING_TRAP_17",
    "EVENT_EXPLODING_TRAP_18",
    "EVENT_EXPLODING_TRAP_19",
    "EVENT_EXPLODING_TRAP_20",
    "EVENT_EXPLODING_TRAP_21",
    "EVENT_EXPLODING_TRAP_22",
]

ROCKET_TRAP_EVENT_FLAG_MAP = {data.event_flags[event]: event for event in TRACKER_ROCKET_TRAP_EVENTS}

TRACKER_SEEN_KANTO_MART_FLAGS = [
    "EVENT_SEEN_MART_VIRIDIAN",
    "EVENT_SEEN_MART_PEWTER",
    "EVENT_SEEN_MART_MT_MOON",
    "EVENT_SEEN_MART_CERULEAN",
    "EVENT_SEEN_MART_VERMILION",
    "EVENT_SEEN_MART_LAVENDER",
    "EVENT_SEEN_MART_SAFFRON",
    "EVENT_SEEN_MART_CELADON_2F_1",
    "EVENT_SEEN_MART_CELADON_2F_2",
    "EVENT_SEEN_MART_CELADON_3F",
    "EVENT_SEEN_MART_CELADON_4F",
    "EVENT_SEEN_MART_CELADON_5F_1",
    "EVENT_SEEN_MART_CELADON_5F_2",
    "EVENT_SEEN_MART_CELADON_VENDING_MACHINE",
    "EVENT_SEEN_MART_FUCHSIA",
    "EVENT_SEEN_MART_INDIGO_PLATEAU",
]

TRACKER_SEEN_JOHTO_MART_FLAGS = [
    "EVENT_SEEN_MART_CHERRYGROVE",
    "EVENT_SEEN_MART_VIOLET",
    "EVENT_SEEN_MART_AZALEA",
    "EVENT_SEEN_MART_KURTS_BALLS",
    "EVENT_SEEN_MART_CIANWOOD",
    "EVENT_SEEN_MART_GOLDENROD_2F_1",
    "EVENT_SEEN_MART_GOLDENROD_2F_2",
    "EVENT_SEEN_MART_GOLDENROD_3F",
    "EVENT_SEEN_MART_GOLDENROD_4F",
    "EVENT_SEEN_MART_GOLDENROD_5F",
    "EVENT_SEEN_MART_GOLDENROD_VENDING_MACHINE",
    "EVENT_SEEN_MART_ROOFTOP_SALE",
    "EVENT_SEEN_MART_UNDERGROUND",
    "EVENT_SEEN_MART_BARGAIN_SHOP",
    "EVENT_SEEN_MART_BLUE_CARD",
    "EVENT_SEEN_MART_OLIVINE",
    "EVENT_SEEN_MART_ECRUTEAK",
    "EVENT_SEEN_MART_MAHOGANY_1",
    "EVENT_SEEN_MART_MAHOGANY_2",
    "EVENT_SEEN_MART_BLACKTHORN",
]

SEEN_KANTO_MART_FLAG_MAP = {data.event_flags[event]: event for event in TRACKER_SEEN_KANTO_MART_FLAGS}
SEEN_JOHTO_MART_FLAG_MAP = {data.event_flags[event]: event for event in TRACKER_SEEN_JOHTO_MART_FLAGS}

TRACKER_KEY_ITEM_FLAGS = [
    "EVENT_ZEPHYR_BADGE_FROM_FALKNER",
    "EVENT_HIVE_BADGE_FROM_BUGSY",
    "EVENT_PLAIN_BADGE_FROM_WHITNEY",
    "EVENT_FOG_BADGE_FROM_MORTY",
    "EVENT_STORM_BADGE_FROM_CHUCK",
    "EVENT_MINERAL_BADGE_FROM_JASMINE",
    "EVENT_GLACIER_BADGE_FROM_PRYCE",
    "EVENT_RISING_BADGE_FROM_CLAIR",
    "EVENT_BOULDER_BADGE_FROM_BROCK",
    "EVENT_CASCADE_BADGE_FROM_MISTY",
    "EVENT_THUNDER_BADGE_FROM_LTSURGE",
    "EVENT_RAINBOW_BADGE_FROM_ERIKA",
    "EVENT_SOUL_BADGE_FROM_JANINE",
    "EVENT_MARSH_BADGE_FROM_SABRINA",
    "EVENT_VOLCANO_BADGE_FROM_BLAINE",
    "EVENT_EARTH_BADGE_FROM_BLUE",

    "EVENT_GOT_RADIO_CARD",
    "EVENT_GOT_MAP_CARD",
    "EVENT_GOT_PHONE_CARD",
    "EVENT_GOT_EXPN_CARD",
    "EVENT_GOT_POKEGEAR",
    "EVENT_GOT_POKEDEX",
    "EVENT_MART_ESCAPE_ROPE",

    "EVENT_RISING_BADGE_FROM_CLAIR_GYM",

    "EVENT_GOT_RED_APRICORN",
    "EVENT_GOT_BLU_APRICORN",
    "EVENT_GOT_YLW_APRICORN",
    "EVENT_GOT_GRN_APRICORN",
    "EVENT_GOT_WHT_APRICORN",
    "EVENT_GOT_BLK_APRICORN",
    "EVENT_GOT_PNK_APRICORN",
]
KEY_ITEM_FLAG_MAP = {data.event_flags[event]: event for event in TRACKER_KEY_ITEM_FLAGS}

TRACKER_EVENT_FLAGS_3 = [
    "EVENT_BOULDER_IN_BLACKTHORN_GYM_1",
    "EVENT_BOULDER_IN_BLACKTHORN_GYM_3",
    "EVENT_BOULDER_IN_ICE_PATH_1A",
    "EVENT_BOULDER_IN_ICE_PATH_2A",
    "EVENT_BOULDER_IN_ICE_PATH_3A",
    "EVENT_BOULDER_IN_ICE_PATH_4A",
    "EVENT_BEAT_ROCKET_GRUNTF_5",
    "EVENT_BEAT_ROCKET_GRUNTM_28",
    "EVENT_BURNED_TOWER_MORTY",
    "EVENT_HEALED_MOOMOO",
    "EVENT_JASMINE_EXPLAINED_AMPHYS_SICKNESS",
    "EVENT_LEARNED_HAIL_GIOVANNI",
    "EVENT_MET_COPYCAT_FOUND_OUT_ABOUT_LOST_ITEM",
    "EVENT_MET_KURT",
    "EVENT_MET_MANAGER_AT_POWER_PLANT",
    "EVENT_MET_ROCKET_GRUNT_AT_CERULEAN_GYM",
    "EVENT_MISTY_RETURNED_TO_GYM",
    "EVENT_USED_THE_CARD_KEY_IN_THE_RADIO_TOWER",
    "EVENT_BEAT_ELITE_4_WILL",
    "EVENT_BEAT_ELITE_4_KOGA",
    "EVENT_BEAT_ELITE_4_BRUNO",
    "EVENT_BEAT_ELITE_4_KAREN",
    "EVENT_TALKED_TO_MOM_AFTER_MYSTERY_EGG_QUEST",
    "EVENT_KURT_RETURNED_GS_BALL",
    "EVENT_SAW_LUCKY_NUMBERS",
]
EVENT_FLAG_MAP_3 = {data.event_flags[event]: event for event in TRACKER_EVENT_FLAGS_3}

# Flags set at new-game and cleared once on completion; send bit=1 when the flag is clear.
INVERTED_TRACKER_FLAGS = {
    "EVENT_BOULDER_IN_ICE_PATH_1A",
    "EVENT_BOULDER_IN_ICE_PATH_2A",
    "EVENT_BOULDER_IN_ICE_PATH_3A",
    "EVENT_BOULDER_IN_ICE_PATH_4A",
}

# (flag_list, flag_map, instance_attr_name, storage_key_suffix)
BITFLAG_STORAGES = [
    (TRACKER_EVENT_FLAGS, EVENT_FLAG_MAP, "local_set_events", "events"),
    (TRACKER_EVENT_FLAGS_2, EVENT_FLAG_MAP_2, "local_set_events_2", "events_2"),
    (TRACKER_STATIC_EVENT_FLAGS, STATIC_EVENT_FLAG_MAP, "local_set_static_events", "statics"),
    (TRACKER_ROCKET_TRAP_EVENTS, ROCKET_TRAP_EVENT_FLAG_MAP, "local_set_rocket_trap_events", "rockettraps"),
    (TRACKER_SEEN_KANTO_MART_FLAGS, SEEN_KANTO_MART_FLAG_MAP, "local_set_seen_kanto_mart_events", "seen_kanto_marts"),
    (TRACKER_SEEN_JOHTO_MART_FLAGS, SEEN_JOHTO_MART_FLAG_MAP, "local_set_seen_johto_mart_events", "seen_johto_marts"),
    (TRACKER_KEY_ITEM_FLAGS, KEY_ITEM_FLAG_MAP, "local_found_key_items", "keys"),
    (TRACKER_EVENT_FLAGS_3, EVENT_FLAG_MAP_3, "local_set_events_3", "events_3"),
]
