name: Fuzz APWorld
on:
  push:
    branches: [ pokecrystal*, future/*, test-ci ]
  pull_request:
    branches: [ pokecrystal*, future/* ]


jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: gerbiljames/ap-actions/fuzz@copy-apworld-source
        with:
          apworld-path: worlds/pokemon_crystal_prerelease
          ap-version: '0.6.5'
          python-version: '3.12'
