name: Release APWorld
on:
  push:
    tags:
      - 'logic-test-[0-9]*'
jobs:
  release:
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: worlds/logic_test
      ap-version: '0.6.7'
      python-version: '3.13'
      prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc')}}
